# Generated by Django 3.1.2 on 2020-10-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iguser',
            name='email',
        ),
    ]
