# Generated by Django 3.1.2 on 2020-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igapp', '0002_remove_iguser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
